services:
  alpha-node-abci:
    build:
      context: abci
      dockerfile: Dockerfile
    container_name: alpha-node-abci
    ports:
      - "26658"
    networks:
      - carmentis-nodes
    #volumes:
    #  - ./out/alpha/abci:/app/data
    environment:
      - PORT=26658
      - NODE_ABCI_STORAGE=/app/data

  alpha-node-cometbft:
    depends_on:
      - alpha-node-abci
    build:
      context: comet
      dockerfile: Dockerfile
    container_name: alpha-node-cometbft
    networks:
      - carmentis-nodes
    #volumes:
    #  - ./out/alpha/cometbft:/app/data
    environment:
      - NODE_MODE=genesis
      - ABCI_ENDPOINT=alpha-node-abci:26658
    ports:
      - "26656"
      - "26657:26657"

networks:
  carmentis-nodes:
    external: true
    name: carmentis-nodes