services:
  alpha-node-abci:
    build:
      context: abci
      dockerfile: Dockerfile
    container_name: alpha-node-abci
    ports:
      - "26658"
    volumes:
      - ./out/alpha/abci:/app/data
    environment:
      - PORT=26658
      - NODE_ABCI_STORAGE=/app/data

  alpha-node-cometbft:
    depends_on:
      - alpha-node-abci
    build:
      context: comet
      dockerfile: Dockerfile
    container_name: alpha-node-cometbft
    volumes:
      - ./out/alpha/cometbft:/app/data
    environment:
      - NODE_MODE=genesis
      - ABCI_ENDPOINT=alpha-node-abci:26658
    ports:
      - "26657:26657"

